//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneMSQFT.Common {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneMSQFT.Common.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT 1MSQFT.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yet somehow bigger..
        /// </summary>
        public static string AboutBlurbFour {
            get {
                return ResourceManager.GetString("AboutBlurbFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Million Square Feet of Culture is a series of guest curated physical spaces that live on through technology..
        /// </summary>
        public static string AboutBlurbOne {
            get {
                return ResourceManager.GetString("AboutBlurbOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There’s no telling what will exist one million square feet from now. Only the size is certain. One million square feet..
        /// </summary>
        public static string AboutBlurbThree {
            get {
                return ResourceManager.GetString("AboutBlurbThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a series of spaces, guest curated by a range of cultural experts. A survey of culture one square foot at a time. It’s square feet for food at an art event. It’s square feet for art at a film event. It’s square feet for film at a fashion event. It’s square feet of culture across all creative disciplines, brought to unexpected places. Physical spaces collected digitally. A gallery of diverse creations, surveyed, shared and held together by digital walls. It’s measurable space, with a touch of the immeas [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutBlurbTwo {
            get {
                return ResourceManager.GetString("AboutBlurbTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Million Square Feet.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR STARTUP.
        /// </summary>
        public static string ClearStartUp {
            get {
                return ResourceManager.GetString("ClearStartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.1msqft.com.
        /// </summary>
        public static string ExitLink_Fallback_Uri {
            get {
                return ResourceManager.GetString("ExitLink_Fallback_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guest curated by.
        /// </summary>
        public static string GuestCurated {
            get {
                return ResourceManager.GetString("GuestCurated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTAGRAM.
        /// </summary>
        public static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://instagram.com/1msqft.
        /// </summary>
        public static string InstagramUrl {
            get {
                return ResourceManager.GetString("InstagramUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem loading One Million Square Feet of Culture. Please check your internet connection..
        /// </summary>
        public static string InternetConnectionFailureMessage {
            get {
                return ResourceManager.GetString("InternetConnectionFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet 1 Million Square Feet Lorem ipsum dolor sit amet 1 Million Square Feet Lorem ipsum dolor sit amet 1 Million Square Feet Lorem ipsum dolor sit amet 1 Million Square Feet Lorem ipsum dolor sit amet 1 Million Square Feet..
        /// </summary>
        public static string IntroBlurb {
            get {
                return ResourceManager.GetString("IntroBlurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN TO START.
        /// </summary>
        public static string PIN {
            get {
                return ResourceManager.GetString("PIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.microsoft.com/privacystatement/en-us/core/default.aspx.
        /// </summary>
        public static string PrivacyPolicyUrl {
            get {
                return ResourceManager.GetString("PrivacyPolicyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSVP for this event.
        /// </summary>
        public static string RSVP {
            get {
                return ResourceManager.GetString("RSVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.1msqft.com.
        /// </summary>
        public static string RSVP_Fallback_Uri {
            get {
                return ResourceManager.GetString("RSVP_Fallback_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem loading One Million Square Feet of Culture. Please try again later..
        /// </summary>
        public static string ServerFailureMessage {
            get {
                return ResourceManager.GetString("ServerFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET AS STARTUP.
        /// </summary>
        public static string SetAsStartUp {
            get {
                return ResourceManager.GetString("SetAsStartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/event/{1}/{2}/{3}/{4}.
        /// </summary>
        public static string ShareEventExhibitUrlFormatRootSlugId {
            get {
                return ResourceManager.GetString("ShareEventExhibitUrlFormatRootSlugId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/event/{1}/{2}.
        /// </summary>
        public static string ShareEventUrlFormatRootSlugId {
            get {
                return ResourceManager.GetString("ShareEventUrlFormatRootSlugId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing to share from 1 Million Square Feet right now..
        /// </summary>
        public static string SharingFailedDisplayText {
            get {
                return ResourceManager.GetString("SharingFailedDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this video from {0}.
        /// </summary>
        public static string SharingTitleVideoFromEventFormat {
            get {
                return ResourceManager.GetString("SharingTitleVideoFromEventFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show.
        /// </summary>
        public static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  since December 2013.
        /// </summary>
        public static string Since {
            get {
                return ResourceManager.GetString("Since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sqft.
        /// </summary>
        public static string SqftFormat {
            get {
                return ResourceManager.GetString("SqftFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to square feet at.
        /// </summary>
        public static string SquareFeet {
            get {
                return ResourceManager.GetString("SquareFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} square feet at {1}.
        /// </summary>
        public static string SquareFeetAtNameFormat {
            get {
                return ResourceManager.GetString("SquareFeetAtNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWITTER.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/1MSQFT.
        /// </summary>
        public static string TwitterUrl {
            get {
                return ResourceManager.GetString("TwitterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there was an error..
        /// </summary>
        public static string UnhandledExceptionTitle {
            get {
                return ResourceManager.GetString("UnhandledExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNPIN FROM START.
        /// </summary>
        public static string UNPIN {
            get {
                return ResourceManager.GetString("UNPIN", resourceCulture);
            }
        }
    }
}
